### ISSUE TITLE
Flashing error

### ISSUE THREAD

**Issue by pirj** [loboris/RePhone_on_Linux#5]
Current HEAD: c143291

Running:

```
./firmwareUploader.py --port /dev/tty.Single\ Port_ --nobattery
```

Getting:

```
DA_CBRInfo
val: 0xc
Traceback (most recent call last):
  File "./firmwareUploader.py", line 1675, in <module>
    main()
  File "./firmwareUploader.py", line 1648, in main
    h.DA_CBRInfo()
  File "./firmwareUploader.py", line 742, in DA_CBRInfo
    raise Exception('no nack')
Exception: no nack
```

The one from http://loboris.eu/rephone/Firmware_update_Linux.tar.gz has some minor differences, but also errors out.

Commenting out the contents of the `DA_CBRInfo` method:

```
DA_SetMemBlock
  RePhone/ROM size: 0x1b60d0
  RePhone/VIVA size: 0x3016ec
  startAddress1 0x20000
  endAddress1 0x1d60cf
Traceback (most recent call last):
  File "./firmwareUploader.py", line 1682, in <module>
    main()
  File "./firmwareUploader.py", line 1657, in main
    h.DA_SetMemBlock(FilenameROM1, FilenameROM2)
  File "./firmwareUploader.py", line 790, in DA_SetMemBlock
    error, = struct.unpack('>I', self.ser.read(4))
struct.error: unpack requires a bytes object of length 4
```

Commenting out also this checks on row 790 and on, geting another failure, commenting out rows 726-732, 810-812, 861-882, still failing.

Wondering if MT has an up to date version of this python script with RePhone roms. Where did you get it?
There's something here: https://github.com/WayenWeng/RePhone_SDK_Bin_Update/tree/master/SEEED02A_DEMO_PCB01_gprs_MT2502_S00.MAUI_11CW1418SP5_W15_29.bin

**Comment by pirj** [comment]
Nevermind. Flashing seems to be buggy in both https://github.com/mandl/LinkIt_Assist_2502/tree/master/FirmwareUploader and https://github.com/Seeed-Studio/Arduino_IDE_for_RePhone/blob/master/hardware/tools/mtk/FirmwareUpdater.exe, only FlashTool_v5.1516.00 works fine (probably because of that option to flash with battery disconnected).
